let token=localStorage.getItem("solo_token"), me=null, socket=null, currentConversation=null;
const $=id=>document.getElementById(id);
function toast(s){$("toast").textContent=s; $("toast").style.cssText="position:fixed;top:15px;right:15px;background:#18233c;padding:12px 16px;border:1px solid #30405f;border-radius:12px;z-index:99";setTimeout(()=>$("toast").textContent="",2500)}
function showAuth(which){$("loginForm").classList.toggle("hidden",which!=="login");$("registerForm").classList.toggle("hidden",which!=="register")}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function boot(){if(!token)return;try{const d=await api("/api/auth/me");me=d.user;openApp();tab("home")}catch{localStorage.removeItem("solo_token");token=null}}
function openApp(){$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("welcomeName").textContent=me.display_name;updateBadge();if(!socket){socket=io();socket.on("connect",()=>socket.emit("identify",{token}));socket.on("new_message",m=>{if(currentConversation===m.conversation_id)loadMessages(currentConversation);});}}
function updateBadge(){const b=$("planBadge");b.textContent=me.plan==="premium"?"👑 PREMIUM":"FREE";b.classList.toggle("premium",me.plan==="premium")}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:$("loginIdentifier").value,password:$("loginPassword").value})});token=d.token;me=d.user;localStorage.setItem("solo_token",token);openApp();tab("home")}catch(e){toast(e.message)}});
$("registerForm").addEventListener("submit",async e=>{e.preventDefault();try{const d=await api("/api/auth/register",{method:"POST",body:JSON.stringify({username:$("regUsername").value,displayName:$("regDisplay").value,email:$("regEmail").value,password:$("regPassword").value,country:$("regCountry").value})});token=d.token;me=d.user;localStorage.setItem("solo_token",token);openApp();tab("home")}catch(e){toast(e.message)}});

function tab(name){
 if(name==="home") home();
 if(name==="discover") discover();
 if(name==="chats") chats();
 if(name==="friends") friends();
 if(name==="rooms") rooms();
 if(name==="premium") premium();
 if(name==="settings") settings();
}
function home(){ $("content").innerHTML=`<div class="hero"><h1>Karibu, ${esc(me.display_name)} 👋</h1><p class="muted">Tafuta mtu wa kuzungumza naye, ongeza friends au jiunge na room.</p><div class="row"><button class="primary" style="width:auto" onclick="randomMatch()">🎯 FIND SOMEONE</button><button onclick="discover()">🔎 DISCOVER</button></div></div><div class="grid"><div class="card"><h3>💬 Chat</h3><p class="muted">Anza private conversation.</p><button onclick="chats()">Open Chats</button></div><div class="card"><h3>👥 Friends</h3><p class="muted">Manage friend requests.</p><button onclick="friends()">Friends</button></div><div class="card"><h3>👑 Premium</h3><p class="muted">Unlock unlimited features.</p><button onclick="premium()">Upgrade</button></div></div>`}
async function discover(){let q=prompt("Search username/name (acha tupu kuona online):");try{const d=await api("/api/chat/users?q="+encodeURIComponent(q||""));$("content").innerHTML=`<div class="spaced"><h2>Discover</h2><button onclick="home()">← Home</button></div><div class="grid">${d.users.map(u=>userCard(u)).join("")}</div>`}catch(e){toast(e.message)}}
function userCard(u){return `<div class="card"><div class="user"><div class="avatar">${u.avatar_url?`<img class="avatar" src="${esc(u.avatar_url)}">`:esc(u.display_name[0]||"?")}</div><div><b>${esc(u.display_name)}</b><div class="muted">@${esc(u.username)} · ${u.online?'<span class="online"></span> Online':'Offline'}</div></div></div><p class="muted">${esc(u.bio||"Hakuna bio")}</p><div class="row"><button onclick="startChat(${u.id})">💬 Chat</button><button onclick="addFriend(${u.id})">👥 Add</button><button onclick="reportUser(${u.id})">⚠️</button></div></div>`}
async function startChat(id){try{const d=await api("/api/chat/conversation",{method:"POST",body:JSON.stringify({userId:id})});openChat(d.conversationId)}catch(e){toast(e.message)}}
async function chats(){const d=await api("/api/chat/conversations");$("content").innerHTML=`<h2>Chats</h2><div class="grid">${d.conversations.map(c=>`<div class="card"><div class="spaced"><b>${esc(c.other?.display_name||"Chat")}</b><button onclick="openChat(${c.id})">Open</button></div><p class="muted">${esc(c.last_message||"No messages")}</p></div>`).join("")||'<div class="card">Hakuna chat bado.</div>'}</div>`}
async function openChat(id){currentConversation=id;const d=await api("/api/chat/messages/"+id);$("content").innerHTML=`<div class="spaced"><h2>💬 Chat</h2><button onclick="chats()">← Chats</button></div><div id="chatbox" class="chatbox">${d.messages.map(msgHtml).join("")}</div><div class="row"><input id="msgInput" placeholder="Andika message..." onkeydown="if(event.key==='Enter')sendMsg()"><button onclick="sendMsg()">SEND</button></div>`;socket.emit("join_conversation",{conversationId:id});}
function msgHtml(m){return `<div class="msg ${m.sender_id===me.id?"mine":""}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleString()}</small></div>`}
async function sendMsg(){const el=$("msgInput");if(!el||!el.value.trim())return;try{const d=await api("/api/chat/message",{method:"POST",body:JSON.stringify({conversationId:currentConversation,body:el.value})});socket.emit("message_sent",d.message);el.value="";loadMessages(currentConversation)}catch(e){toast(e.message)}}
async function loadMessages(id){const d=await api("/api/chat/messages/"+id);const box=$("chatbox");if(box){box.innerHTML=d.messages.map(msgHtml).join("");box.scrollTop=box.scrollHeight}}
async function friends(){const d=await api("/api/chat/friends");$("content").innerHTML=`<h2>Friends</h2><div class="grid">${d.friends.map(u=>userCard(u)).join("")||'<div class="card">Hakuna friends bado.</div>'}</div>`}
async function addFriend(id){try{await api("/api/chat/friends/request",{method:"POST",body:JSON.stringify({userId:id})});toast("Friend request imetumwa")}catch(e){toast(e.message)}}
async function reportUser(id){const reason=prompt("Sababu ya report?");if(!reason)return;try{await api("/api/chat/report",{method:"POST",body:JSON.stringify({reportedId:id,reason})});toast("Report imetumwa")}catch(e){toast(e.message)}}
async function rooms(){const d=await api("/api/chat/rooms");$("content").innerHTML=`<h2>Rooms</h2><div class="grid">${d.rooms.map(r=>`<div class="card"><h3>${esc(r.name)}</h3><p class="muted">${esc(r.description)}</p><button onclick="joinRoom(${r.id})">JOIN</button></div>`).join("")}</div>`}
async function joinRoom(id){try{await api("/api/chat/rooms/"+id+"/join",{method:"POST"});toast("Umejiunga na room")}catch(e){toast(e.message)}}
async function premium(){const d=await api("/api/payments/plans");$("content").innerHTML=`<div class="hero"><h1>👑 SOLO CHAT PREMIUM</h1><p>Unlock unlimited chatting and premium features.</p></div><div class="plans">${d.plans.map(p=>`<div class="plan"><h2>${esc(p.name)}</h2><strong>TZS ${Number(p.price).toLocaleString()}</strong><p>${p.duration_days} days</p><p class="muted">${esc(p.features)}</p><button class="primary" onclick="pay(${p.id})">UPGRADE NOW</button></div>`).join("")}</div>`}
async function pay(planId){const phone=prompt("Weka namba ya simu ya malipo:");if(!phone)return;try{const d=await api("/api/payments/create",{method:"POST",body:JSON.stringify({planId,phone})});toast("Thibitisha malipo kwenye simu yako.");await watchPayment(d.payment.provider_order_id)}catch(e){toast(e.message)}}
async function watchPayment(orderId){for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,5000));try{const d=await api("/api/payments/status/"+encodeURIComponent(orderId));if(d.payment.status==="completed"){const meD=await api("/api/auth/me");me=meD.user;updateBadge();toast("🎉 Premium activated!");premium();return}if(["failed","cancelled"].includes(d.payment.status)){toast("Payment failed");return}}catch{}}toast("Payment bado haijathibitishwa. Angalia Transactions baadaye.")}
async function settings(){ $("content").innerHTML=`<h2>Settings</h2><div class="card"><h3>Profile</h3><input id="setName" value="${esc(me.display_name)}" placeholder="Display name"><input id="setUsername" value="${esc(me.username)}" placeholder="Username"><input id="setCountry" value="${esc(me.country||"")}" placeholder="Country"><textarea id="setBio" placeholder="Bio">${esc(me.bio||"")}</textarea><input id="setInterests" value="${esc(me.interests||"")}" placeholder="Interests"><input id="setAvatar" value="${esc(me.avatar_url||"")}" placeholder="Avatar URL"><button onclick="saveProfile()">SAVE PROFILE</button></div><div class="card"><h3>🔐 Password</h3><input id="oldPass" type="password" placeholder="Current password"><input id="newPass" type="password" placeholder="New password"><button onclick="changePass()">CHANGE PASSWORD</button></div><div class="card"><h3>💳 Payments</h3><button onclick="payments()">Transaction History</button></div><div class="card"><h3>🔔 Notifications</h3><button onclick="loadNotifications()">View Notifications</button></div>`}
async function saveProfile(){try{const d=await api("/api/auth/profile",{method:"PUT",body:JSON.stringify({displayName:$("setName").value,username:$("setUsername").value,country:$("setCountry").value,bio:$("setBio").value,interests:$("setInterests").value,avatarUrl:$("setAvatar").value})});me=d.user;$("welcomeName").textContent=me.display_name;toast("Profile saved")}catch(e){toast(e.message)}}
async function changePass(){try{await api("/api/auth/password",{method:"PUT",body:JSON.stringify({currentPassword:$("oldPass").value,newPassword:$("newPass").value})});toast("Password changed")}catch(e){toast(e.message)}}
async function payments(){const d=await api("/api/payments/mine");$("content").innerHTML=`<h2>Transactions</h2><div class="card">${d.payments.map(p=>`<div class="spaced" style="padding:10px 0;border-bottom:1px solid var(--line)"><span>${esc(p.name)} · TZS ${Number(p.amount).toLocaleString()}</span><span>${esc(p.status)}</span></div>`).join("")||"Hakuna transaction."}</div>`}
async function loadNotifications(){const d=await api("/api/chat/notifications");$("notifCount").textContent=d.notifications.filter(n=>!n.read).length;tabNotifications(d.notifications)}
function tabNotifications(ns){$("content").innerHTML=`<h2>Notifications</h2>${ns.map(n=>`<div class="card"><b>${esc(n.title)}</b><p class="muted">${esc(n.body)}</p></div>`).join("")||'<div class="card">No notifications.</div>'}`}
async function randomMatch(){try{const d=await api("/api/chat/users?q=");const candidates=d.users.filter(u=>u.online);if(!candidates.length)return toast("Hakuna mtu online kwa sasa.");const u=candidates[Math.floor(Math.random()*candidates.length)];if(me.plan!=="premium"){const used=Number(localStorage.getItem("free_matches")||0);if(used>=5)return premium();localStorage.setItem("free_matches",used+1)}startChat(u.id)}catch(e){toast(e.message)}}
async function logout(){try{await api("/api/auth/logout",{method:"POST"})}catch{}localStorage.removeItem("solo_token");location.reload()}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
boot();
